server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client: # 客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: gateway-9527 #注册到eureka中的实例名
    prefer-ip-address: true # 访问路径可以显示ip地址

zuul:
  ignored-services: "*"
#  ignored-services: microservicecloud-dept
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

info:
  app.name: atguigu-microservicecloud
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}  #这里按照视频中的$project.artifactId$不能获取到值
  build.version: ${project.version}

