server:
  port: 81

spring:
  application:
    name: microservicecloud-consumer-dept

eureka:
   client: # 客户端注册进eureka服务列表
     service-url:
#       defaultZone: http://localhost:7001/eureka  # 7001eureka注册中心地址：注册本服务提供者
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
   instance:
     instance-id: microservicecloud-consumer-dept80 #注册到eureka中的实例名
     prefer-ip-address: true # 访问路径可以显示ip地址

info:
   app.name: huawei-microservicecloud
   company.name: www.huawei.com
   build.artifactId: ${project.artifactId}  #这里按照视频中的$project.artifactId$不能获取到值
   build.version: ${project.version}